In [1]:
#The best recall score is 0.75 

#since the high count is only 12, if I split it into 70-30 ratio I'm getting recall as 0.
#Hence I have taken the complete data without splitting it into train and test#

In [2]:
#The Decision tree gave the highest recal score

In [3]:
#I have use all the parameters

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
from scipy.stats import zscore
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [5]:
df=pd.read_csv('Absenteeism_at_work.csv')

In [6]:
df.shape

(740, 21)

In [7]:
df.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day      ...       Disciplinary failure  Education  Son  \
0                 239.554     ...                          0          1    2   
1                 239.554     ...                          1          1    1   
2                 239.554     ...                          0          1    0   
3                 239.554     ...                          0          1    2   
4                 239.554     ...                          0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism  
0          low  
1          low  
2          low  
3          low  
4          low  

[5 rows x 21 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
ID                                 740 non-null int64
Reason for absence                 740 non-null int64
Month of absence                   740 non-null int64
Day of the week                    740 non-null int64
Seasons                            740 non-null int64
Transportation expense             740 non-null int64
Distance from Residence to Work    740 non-null int64
Service time                       740 non-null int64
Age                                740 non-null int64
Work load Average/day              740 non-null float64
Hit target                         740 non-null int64
Disciplinary failure               740 non-null int64
Education                          740 non-null int64
Son                                740 non-null int64
Social drinker                     740 non-null int64
Social smoker                      740 non-null int64
Pet                          

In [9]:
df['Absenteeism'].value_counts()

low       677
medium     51
high       12
Name: Absenteeism, dtype: int64

In [10]:
df=df.drop('ID',axis=1)

In [11]:
df.describe().T

count        mean        std      min  \
Reason for absence               740.0   19.216216   8.433406    0.000   
Month of absence                 740.0    6.324324   3.436287    0.000   
Day of the week                  740.0    3.914865   1.421675    2.000   
Seasons                          740.0    2.544595   1.111831    1.000   
Transportation expense           740.0  221.329730  66.952223  118.000   
Distance from Residence to Work  740.0   29.631081  14.836788    5.000   
Service time                     740.0   12.554054   4.384873    1.000   
Age                              740.0   36.450000   6.478772   27.000   
Work load Average/day            740.0  271.490235  39.058116  205.917   
Hit target                       740.0   94.587838   3.779313   81.000   
Disciplinary failure             740.0    0.054054   0.226277    0.000   
Education                        740.0    1.291892   0.673238    1.000   
Son                              740.0    1.018919   1.098489    0.000   
Social drinker                   740.0    0.567568   0.495749    0.000   
Social smoker                    740.0    0.072973   0.260268    0.000   
Pet                              740.0    0.745946   1.318258    0.000   
Weight                           740.0   79.035135  12.883211   56.000   
Height                           740.0  172.114865   6.034995  163.000   
Body mass index                  740.0   26.677027   4.285452   19.000   

                                     25%      50%      75%      max  
Reason for absence                13.000   23.000   26.000   28.000  
Month of absence                   3.000    6.000    9.000   12.000  
Day of the week                    3.000    4.000    5.000    6.000  
Seasons                            2.000    3.000    4.000    4.000  
Transportation expense           179.000  225.000  260.000  388.000  
Distance from Residence to Work   16.000   26.000   50.000   52.000  
Service time                       9.000   13.000   16.000   29.000  
Age                               31.000   37.000   40.000   58.000  
Work load Average/day            244.387  264.249  294.217  378.884  
Hit target                        93.000   95.000   97.000  100.000  
Disciplinary failure               0.000    0.000    0.000    1.000  
Education                          1.000    1.000    1.000    4.000  
Son                                0.000    1.000    2.000    4.000  
Social drinker                     0.000    1.000    1.000    1.000  
Social smoker                      0.000    0.000    0.000    1.000  
Pet                                0.000    0.000    1.000    8.000  
Weight                            69.000   83.000   89.000  108.000  
Height                           169.000  170.000  172.000  196.000  
Body mass index                   24.000   25.000   31.000   38.000

In [12]:
for feature in df.columns: 
    if df[feature].dtype == 'object':
        df[feature] = pd.Categorical(df[feature]).codes 

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 20 columns):
Reason for absence                 740 non-null int64
Month of absence                   740 non-null int64
Day of the week                    740 non-null int64
Seasons                            740 non-null int64
Transportation expense             740 non-null int64
Distance from Residence to Work    740 non-null int64
Service time                       740 non-null int64
Age                                740 non-null int64
Work load Average/day              740 non-null float64
Hit target                         740 non-null int64
Disciplinary failure               740 non-null int64
Education                          740 non-null int64
Son                                740 non-null int64
Social drinker                     740 non-null int64
Social smoker                      740 non-null int64
Pet                                740 non-null int64
Weight                       

In [14]:
train_char_label = ['0','1','2'] 

In [15]:
df['Absenteeism'].value_counts() 
# 0 - High 
# 1 - low
# 2 - medium

1    677
2     51
0     12
Name: Absenteeism, dtype: int64

In [16]:
df.corr()

Reason for absence  Month of absence  \
Reason for absence                         1.000000         -0.083858   
Month of absence                          -0.083858          1.000000   
Day of the week                            0.116319         -0.006528   
Seasons                                   -0.117925          0.407770   
Transportation expense                    -0.119381          0.137525   
Distance from Residence to Work            0.161831         -0.003887   
Service time                               0.048425         -0.062862   
Age                                       -0.078608         -0.001520   
Work load Average/day                     -0.123472         -0.169989   
Hit target                                 0.088943         -0.460453   
Disciplinary failure                      -0.545054          0.107946   
Education                                 -0.047357         -0.066128   
Son                                       -0.055364          0.079031   
Social drinker                             0.065441          0.056226   
Social smoker                             -0.115702         -0.038603   
Pet                                       -0.055911          0.047787   
Weight                                    -0.000269          0.023278   
Height                                    -0.079267         -0.068942   
Body mass index                            0.037205          0.051046   
Absenteeism                               -0.094109         -0.032429   

                                 Day of the week   Seasons  \
Reason for absence                      0.116319 -0.117925   
Month of absence                       -0.006528  0.407770   
Day of the week                         1.000000  0.046493   
Seasons                                 0.046493  1.000000   
Transportation expense                  0.033988  0.036995   
Distance from Residence to Work         0.118026 -0.063108   
Service time                            0.021252 -0.010904   
Age                                     0.004459 -0.012089   
Work load Average/day                   0.015646  0.150439   
Hit target                              0.030986 -0.061154   
Disciplinary failure                   -0.015120  0.151766   
Education                               0.058516 -0.002951   
Son                                     0.098079  0.046950   
Social drinker                          0.041772 -0.045982   
Social smoker                           0.013156 -0.048671   
Pet                                    -0.028885  0.012356   
Weight                                 -0.128980 -0.026278   
Height                                 -0.082133 -0.033737   
Body mass index                        -0.103578 -0.011031   
Absenteeism                            -0.055284  0.020177   

                                 Transportation expense  \
Reason for absence                            -0.119381   
Month of absence                               0.137525   
Day of the week                                0.033988   
Seasons                                        0.036995   
Transportation expense                         1.000000   
Distance from Residence to Work                0.262183   
Service time                                  -0.349887   
Age                                           -0.227542   
Work load Average/day                          0.005438   
Hit target                                    -0.080193   
Disciplinary failure                           0.109222   
Education                                     -0.055065   
Son                                            0.383001   
Social drinker                                 0.145117   
Social smoker                                  0.044356   
Pet                                            0.400080   
Weight                                        -0.207435   
Height                                        -0.194496   
Body mass index                               -0.136517   
Absenteeism     

In [17]:
from sklearn.tree import DecisionTreeClassifier 

In [18]:
X =  df.drop("Absenteeism", axis=1)
y =  df.pop("Absenteeism")

In [19]:
X.head()

Reason for absence  Month of absence  Day of the week  Seasons  \
0                  26                 7                3        1   
1                   0                 7                3        1   
2                  23                 7                4        1   
3                   7                 7                5        1   
4                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   Hit target  Disciplinary failure  Education  Son  \
0                 239.554          97                     0          1    2   
1                 239.554          97                     1          1    1   
2                 239.554          97                     0          1    0   
3                 239.554          97                     0          1    2   
4                 239.554          97                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  
0               1              0    1      90     172               30  
1               1              0    0      98     178               31  
2               1              0    0      89     170               31  
3               1              1    0      68     168               24  
4               1              0    1      90     172               30

In [20]:
train_set, test_set, train_labels, test_labels = train_test_split(X, y, test_size=0.30, random_state=1)

In [21]:
dt_model = DecisionTreeClassifier(criterion = 'entropy' )

In [22]:
dt_model.fit(train_set, train_labels)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [23]:
dt_model.score(test_set , test_labels) 

0.8738738738738738

In [24]:
predicted_test_labels = dt_model.predict(test_set)


In [25]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(test_labels,predicted_test_labels)

conf_matrix

array([[  0,   3,   0],
       [  4, 191,   8],
       [  2,  11,   3]], dtype=int64)

In [26]:
print(metrics.classification_report(test_labels, predicted_test_labels))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.93      0.94      0.94       203
           2       0.27      0.19      0.22        16

   micro avg       0.87      0.87      0.87       222
   macro avg       0.40      0.38      0.39       222
weighted avg       0.87      0.87      0.87       222



In [27]:
from sklearn.metrics import accuracy_score,cohen_kappa_score
cohen_kappa_score(test_labels, predicted_test_labels)

0.16842809364548483

In [28]:
from IPython.display import Image  
#import pydotplus as pydot
from sklearn import tree
from os import system

Credit_Tree_File = open('Wine.dot','w')
dot_data = tree.export_graphviz(dt_model, out_file=Credit_Tree_File, feature_names = list(train_set), class_names = list(train_char_label))

Credit_Tree_File.close()


print (pd.DataFrame(dt_model.feature_importances_, columns = ["Imp"], index = train_set.columns)) 


                                      Imp
Reason for absence               0.306260
Month of absence                 0.072763
Day of the week                  0.062673
Seasons                          0.000000
Transportation expense           0.017918
Distance from Residence to Work  0.082775
Service time                     0.017416
Age                              0.020250
Work load Average/day            0.196713
Hit target                       0.092303
Disciplinary failure             0.000000
Education                        0.000000
Son                              0.011413
Social drinker                   0.035828
Social smoker                    0.000000
Pet                              0.012422
Weight                           0.008285
Height                           0.037951
Body mass index                  0.025030


In [29]:
### without train and test

In [30]:
dt_model1 = DecisionTreeClassifier(criterion = 'entropy' )
dt_model1.fit(X, y)
dt_model1.score(X , y) 
predicted_test_labels = dt_model.predict(X)


In [31]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y,predicted_test_labels)

conf_matrix

array([[  9,   3,   0],
       [  5, 664,   8],
       [  2,  14,  35]], dtype=int64)

In [32]:
print(metrics.classification_report(y, predicted_test_labels))

              precision    recall  f1-score   support

           0       0.56      0.75      0.64        12
           1       0.98      0.98      0.98       677
           2       0.81      0.69      0.74        51

   micro avg       0.96      0.96      0.96       740
   macro avg       0.78      0.81      0.79       740
weighted avg       0.96      0.96      0.96       740



In [33]:
                             # using naive bayes algorithm

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
model = GaussianNB()
model.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [36]:
expected = y
predicted = model.predict(X)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       0.09      0.67      0.16        12
           1       0.99      0.43      0.60       677
           2       0.11      0.80      0.20        51

   micro avg       0.46      0.46      0.46       740
   macro avg       0.40      0.63      0.32       740
weighted avg       0.91      0.46      0.56       740

[[  8   1   3]
 [ 70 289 318]
 [  8   2  41]]


In [37]:
## Running all the classification algorithms

In [38]:
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [39]:
lr=LogisticRegression()
rf=RandomForestClassifier()
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
nb=GaussianNB()
models = [lr, nb, knn, dt, rf]
for mod in models : 
    print(mod)
    print("\n")
    mod.fit(X,y)
    print(mod.score(X,y))
    ypred = mod.predict(X)
    mod.score(X , y) 
    conf_matrix = metrics.confusion_matrix(y, ypred)
    print(conf_matrix)
    print(metrics.classification_report(y, ypred))
    print("\n \n")

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)


0.9162162162162162

C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\me


[[  0  12   0]
 [  0 676   1]
 [  0  49   2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.92      1.00      0.96       677
           2       0.67      0.04      0.07        51

   micro avg       0.92      0.92      0.92       740
   macro avg       0.53      0.35      0.34       740
weighted avg       0.89      0.92      0.88       740


 

GaussianNB(priors=None, var_smoothing=1e-09)


0.45675675675675675
[[  8   1   3]
 [ 70 289 318]
 [  8   2  41]]
              precision    recall  f1-score   support

           0       0.09      0.67      0.16        12
           1       0.99      0.43      0.60       677
           2       0.11      0.80      0.20        51

   micro avg       0.46      0.46      0.46       740
   macro avg       0.40      0.63      0.32       740
weighted avg       0.91      0.46      0.56       740


 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski

C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
