In [8]:
import numpy as np
import xgboost as xgb
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [181]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [182]:
# use DMatrix for xgbosot
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

In [183]:
dtrain

In [184]:
#DMatrix--its a datastructure used for XGboost

# set xgboost params
param = {
    'max_depth': 3,  # the maximum depth of each tree
    'eta': 0.3,  # the learning rate
    'silent': 1,  # logging mode - 1 = quiet / 0 = loud
    'objective': 'multi:softmax',#'multi:softprob',  # error evaluation for multiclass training
    ### binary:logistic , multi:softmax'#multi:softmax
    'num_class': 3}  # the number of classes that exist in this datset
#if binary:logistic no need of num_class
num_round = 20  # the number of training iterations

In [186]:
# training and testing
bst = xgb.train(param, dtrain, num_round)
preds = bst.predict(dtest)

In [187]:
#print(bst.(y_test,preds)) for softprob

In [188]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [194]:
# for softmax we get accuracy
print(accuracy_score(y_test,preds))

1.0


In [193]:
print(confusion_matrix(y_test,preds))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [195]:
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

   micro avg       1.00      1.00      1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [197]:
## try xgb.cv

# extracting most confident predictions
best_preds = np.asarray([np.argmax(line) for line in preds])
print("Precision:", precision_score(y_test, best_preds, average='macro'))



Precision: 0.1111111111111111
