In [10]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split,cross_val_score,KFold
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,AdaBoostClassifier
from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.datasets import load_iris
import sklearn.model_selection
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression
import string
import xgboost

In [3]:
train=pd.read_csv('C:\\Users\\Ashok\\Desktop\\Ensemble Techniques\\XGBoost\\recommendation system\\train.csv')
test=pd.read_csv('C:\\Users\\Ashok\\Desktop\\Ensemble Techniques\\XGBoost\\recommendation system\\test.csv')

In [4]:
train.shape

(20514, 18)

In [5]:
train.isnull().sum()

feature1         0
feature2         0
feature3         0
feature4         0
feature5         0
feature6         0
feature7         0
feature8         0
target           0
feature1-code    0
feature2-code    0
feature3-code    0
feature4-code    0
feature5-code    0
feature6-code    0
feature7-code    0
feature8-code    0
target-code      0
dtype: int64

In [6]:
train.head()

feature1 feature2 feature3 feature4 feature5 feature6 feature7 feature8  \
0    f1102      f20    f3173    f4619    f5139      f60  item118  item118   
1    f1343      f20    f3881   f41745    f5160      f60   item49  item124   
2     f120      f20     f324   f41625    f5136      f60   item43    item4   
3     f147      f20    f3409    f4877    f5320      f60   item54   item54   
4     f197      f20    f3257    f4299    f5208      f60   item47   item47   

    target  feature1-code  feature2-code  feature3-code  feature4-code  \
0   item14             92              1            144            371   
1  item120              5              1              7              7   
2   item44              4              1              4             97   
3   item54             56              1             81            131   
4  item126             10              1            304            409   

   feature5-code  feature6-code  feature7-code  feature8-code  target-code  
0            128              1             11             11           49  
1              7              1             45            100          142  
2             78              1              2             82           64  
3             71              1             46             46           46  
4            129              1              3              3           68

In [8]:
train['target-code'].unique()

array([ 49, 142,  64,  46,  68, 129, 158,  21,  22,  60,   8,  42,  30,
        69,  24,  27,  23,  81, 166,  51,  83,  16,  54,  29,  31,  38,
        12,  66,  86,  45,  70,  96,   6,  35, 106, 105, 117,  72,  44,
        53,  10, 113,  41,   5,  17,  93,  59,  33,  47, 108,  20,  88,
        37,  82,  15,  95,  11, 125, 162,  63,   1,   4,  55, 164, 167,
        19, 104, 109,  94,  75,  28,   3,  92,  84,  18,  77,  56, 144,
       143,  13, 107,  57,  34, 170,  91,  48,  39,  14,  58,  50, 114,
        25, 122,  90, 101, 132, 126, 151, 131, 130,  78, 139, 110,  76,
       168,   9,  99,  62, 100, 120, 152, 155, 135,  32, 128, 146, 163,
         7, 112,  43, 133,  26,  98,   2, 102, 137, 141, 127, 134,  89,
       154,  74,  65,  67,  79,  71, 123, 138, 111,  52, 153,  73, 148,
       116, 115,  87,  40, 140, 103, 161,  36, 165,  97, 159,  80, 149,
       147, 121, 124, 160, 150, 118, 145, 157, 136, 156,  61, 119,  85,
       173, 172, 171, 169], dtype=int64)

In [11]:
featurecolumns = ['feature1-code',
              'feature2-code',
              'feature3-code',
              'feature4-code',
              'feature5-code',
              'feature6-code',
              'feature7-code',
              'feature8-code']

In [12]:
X_train = train[featurecolumns].values
Y_train = train['target-code'].values
X_test = test[featurecolumns].values
Y_test = test['target-code'].values


In [16]:
rf=RandomForestClassifier()
Ada=AdaBoostClassifier()
models = [rf,Ada]
for mod in models : 
    print(mod)
    print("\n")
    mod.fit(X_train,Y_train)
    ypred = mod.predict(X_test)
    print(accuracy_score(Y_test,ypred))
    conf_matrix = confusion_matrix(Y_test, ypred)
    print(conf_matrix)
    print(classification_report(Y_test, ypred))
    print("\n \n")

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)




C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.1604601286800546
[[13  0  3 ...  0  0  0]
 [ 1  2  0 ...  0  0  0]
 [ 1  0  5 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           1       0.15      0.18      0.16        74
           2       0.07      0.06      0.07        31
           3       0.06      0.07      0.06        69
           4       0.23      0.27      0.25        73
           5       0.24      0.29      0.26       124
           6       0.07      0.11      0.08        76
           7       0.09      0.10      0.09        31
           8       0.14      0.21      0.17       156
           9       0.15      0.12      0.13        25
          10       0.11      0.14      0.12        36
          11       0.21      0.22      0.21        37
          12       0.18      0.22      0.20       249
          13       0.24      0.32      0.28       140
          14       0.12      0.12      0.12        16
          15  

C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.07876779099239618
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        74
           2       0.00      0.00      0.00        31
           3       0.00      0.00      0.00        69
           4       0.00      0.00      0.00        73
           5       0.00      0.00      0.00       124
           6       0.00      0.00      0.00        76
           7       0.00      0.00      0.00        31
           8       0.09      0.38      0.14       156
           9       0.00      0.00      0.00        25
          10       0.00      0.00      0.00        36
          11       0.00      0.00      0.00        37
          12       0.07      0.48      0.12       249
          13       0.00      0.00      0.00       140
          14       0.00      0.00      0.00        16
          15       0.00      0.00      0.00      

C:\Users\Ashok\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
