In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold,cross_val_score
from sklearn.model_selection import train_test_split
import seaborn as sns

In [2]:
Devanagiri=pd.read_csv('C:\\Users\\Ashok\\Desktop\\Ensemble Techniques\\data.csv')

In [3]:
Devanagiri.shape

(92000, 1025)

In [4]:
Devanagiri.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   pixel_0006  pixel_0007  pixel_0008  pixel_0009       ...         \
0           0           0           0           0       ...          
1           0           0           0           0       ...          
2           0           0           0           0       ...          
3           0           0           0           0       ...          
4           0           0           0           0       ...          

   pixel_1015  pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   pixel_1021  pixel_1022  pixel_1023        character  
0           0           0           0  character_01_ka  
1           0           0           0  character_01_ka  
2           0           0           0  character_01_ka  
3           0           0           0  character_01_ka  
4           0           0           0  character_01_ka  

[5 rows x 1025 columns]

In [ ]:
Devanagiri.isnull().sum()

In [6]:
Devanagiri['character'].unique()

array(['character_01_ka', 'character_02_kha', 'character_03_ga',
       'character_04_gha', 'character_05_kna', 'character_06_cha',
       'character_07_chha', 'character_08_ja', 'character_09_jha',
       'character_10_yna', 'character_11_taamatar', 'character_12_thaa',
       'character_13_daa', 'character_14_dhaa', 'character_15_adna',
       'character_16_tabala', 'character_17_tha', 'character_18_da',
       'character_19_dha', 'character_20_na', 'character_21_pa',
       'character_22_pha', 'character_23_ba', 'character_24_bha',
       'character_25_ma', 'character_26_yaw', 'character_27_ra',
       'character_28_la', 'character_29_waw', 'character_30_motosaw',
       'character_31_petchiryakha', 'character_32_patalosaw',
       'character_33_ha', 'character_34_chhya', 'character_35_tra',
       'character_36_gya', 'digit_0', 'digit_1', 'digit_2', 'digit_3',
       'digit_4', 'digit_5', 'digit_6', 'digit_7', 'digit_8', 'digit_9'],
      dtype=object)

In [7]:
Devanagiri['character'].value_counts()

character_10_yna             2000
character_30_motosaw         2000
character_08_ja              2000
character_35_tra             2000
digit_4                      2000
character_19_dha             2000
character_26_yaw             2000
character_24_bha             2000
character_01_ka              2000
character_20_na              2000
character_06_cha             2000
character_27_ra              2000
digit_1                      2000
character_09_jha             2000
character_21_pa              2000
character_32_patalosaw       2000
character_17_tha             2000
character_02_kha             2000
character_12_thaa            2000
character_05_kna             2000
character_36_gya             2000
character_31_petchiryakha    2000
character_33_ha              2000
digit_3                      2000
digit_6                      2000
character_22_pha             2000
character_28_la              2000
digit_5                      2000
character_11_taamatar        2000
character_34_c

In [8]:
X=Devanagiri.drop('character',axis=1)
Y=Devanagiri['character']

In [9]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.3,random_state=2)

In [10]:
DT=DecisionTreeClassifier()

In [11]:
DT.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [12]:
ypred=DT.predict(xtest)

In [13]:
print(accuracy_score(ytest,ypred))

0.5848188405797101


In [14]:
print(confusion_matrix(ytest,ypred))

[[355   7   7 ...   9   2   2]
 [  6 202  11 ...   2   1   3]
 [  1  12 319 ...   1   3   1]
 ...
 [  4   3   0 ... 458   1   2]
 [  1   0   4 ...   3 501   1]
 [  3   2   3 ...   4   0 429]]


#  We will take only data target which is digit 0 and digit1

In [37]:
Data=Devanagiri[Devanagiri['character']=='digit_0']

In [38]:
Data.shape

(2000, 1025)

In [39]:
Data.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
72000           0           0           0           0           0           0   
72001           0           0           0           0           0           0   
72002           0           0           0           0           0           0   
72003           0           0           0           0           0           0   
72004           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009    ...      pixel_1015  \
72000           0           0           0           0    ...               0   
72001           0           0           0           0    ...               0   
72002           0           0           0           0    ...               0   
72003           0           0           0           0    ...               0   
72004           0           0           0           0    ...               0   

       pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  pixel_1021  \
72000           0           0           0           0           0           0   
72001           0           0           0           0           0           0   
72002           0           0           0           0           0           0   
72003           0           0           0           0           0           0   
72004           0           0           0           0           0           0   

       pixel_1022  pixel_1023  character  
72000           0           0    digit_0  
72001           0           0    digit_0  
72002           0           0    digit_0  
72003           0           0    digit_0  
72004           0           0    digit_0  

[5 rows x 1025 columns]

In [40]:
Data1= Devanagiri[Devanagiri['character']=='digit_1']

In [41]:
Data1.shape

(2000, 1025)

In [42]:
Data1.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
74000           0           0           0           0           0           0   
74001           0           0           0           0           0           0   
74002           0           0           0           0           0           0   
74003           0           0           0           0           0           0   
74004           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009    ...      pixel_1015  \
74000           0           0           0           0    ...               0   
74001           0           0           0           0    ...               0   
74002           0           0           0           0    ...               0   
74003           0           0           0           0    ...               0   
74004           0           0           0           0    ...               0   

       pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  pixel_1021  \
74000           0           0           0           0           0           0   
74001           0           0           0           0           0           0   
74002           0           0           0           0           0           0   
74003           0           0           0           0           0           0   
74004           0           0           0           0           0           0   

       pixel_1022  pixel_1023  character  
74000           0           0    digit_1  
74001           0           0    digit_1  
74002           0           0    digit_1  
74003           0           0    digit_1  
74004           0           0    digit_1  

[5 rows x 1025 columns]

In [47]:
NewData=pd.concat([Data,Data1],axis=0)

In [48]:
NewData.shape

(4000, 1025)

In [49]:
NewData.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
72000           0           0           0           0           0           0   
72001           0           0           0           0           0           0   
72002           0           0           0           0           0           0   
72003           0           0           0           0           0           0   
72004           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009    ...      pixel_1015  \
72000           0           0           0           0    ...               0   
72001           0           0           0           0    ...               0   
72002           0           0           0           0    ...               0   
72003           0           0           0           0    ...               0   
72004           0           0           0           0    ...               0   

       pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  pixel_1021  \
72000           0           0           0           0           0           0   
72001           0           0           0           0           0           0   
72002           0           0           0           0           0           0   
72003           0           0           0           0           0           0   
72004           0           0           0           0           0           0   

       pixel_1022  pixel_1023  character  
72000           0           0    digit_0  
72001           0           0    digit_0  
72002           0           0    digit_0  
72003           0           0    digit_0  
72004           0           0    digit_0  

[5 rows x 1025 columns]

# Decision Tree

In [50]:
X1=NewData.drop('character',axis=1)
Y1=NewData['character']

In [51]:
xtrain,xtest,ytrain,ytest=train_test_split(X1,Y1,test_size=0.3,random_state=2)

In [52]:
DT=DecisionTreeClassifier()

In [53]:
DT.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [54]:
ypred=DT.predict(xtest)

In [55]:
print(accuracy_score(ytest,ypred))

0.9925


In [56]:
print(confusion_matrix(ytest,ypred))

[[597   5]
 [  4 594]]


In [62]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

     digit_0       0.99      0.99      0.99       602
     digit_1       0.99      0.99      0.99       598

   micro avg       0.99      0.99      0.99      1200
   macro avg       0.99      0.99      0.99      1200
weighted avg       0.99      0.99      0.99      1200



# Gradiant Boosting

In [57]:
from sklearn.ensemble import GradientBoostingClassifier

In [58]:
GD=GradientBoostingClassifier(n_estimators=10,learning_rate=0.1)
#n_estimators==number of iterations
#learning_rate=0.1
#base model is DT by default
#here nb i have given as base estimator
model = GD.fit(xtrain, ytrain)

y_pred = model.predict(xtest)

In [59]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(ytest, y_pred))

Accuracy: 0.9941666666666666


In [60]:
print(confusion_matrix(ytest,y_pred))

[[598   4]
 [  3 595]]


In [63]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

     digit_0       1.00      0.99      0.99       602
     digit_1       0.99      0.99      0.99       598

   micro avg       0.99      0.99      0.99      1200
   macro avg       0.99      0.99      0.99      1200
weighted avg       0.99      0.99      0.99      1200



# Here we are getting high accuracy becasue all the values are categorical values

# digit1 and digit9

In [64]:
Data2= Devanagiri[Devanagiri['character']=='digit_1']

In [65]:
Data9= Devanagiri[Devanagiri['character']=='digit_9']

In [67]:
DataNew=pd.concat([Data2,Data9],axis=0)

In [68]:
DataNew.shape

(4000, 1025)

In [70]:
X2=DataNew.drop('character',axis=1)
Y2=DataNew['character']

In [76]:
xtrain1,xtest1,ytrain1,ytest1=train_test_split(X2,Y2,test_size=0.3,random_state=2)

In [78]:
GD=GradientBoostingClassifier(n_estimators=10,learning_rate=0.1)
#n_estimators==number of iterations
#learning_rate=0.1
#base model is DT by default
#here nb i have given as base estimator
model = GD.fit(xtrain1, ytrain1)

y_pred1 = model.predict(xtest1)

In [79]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(ytest1, y_pred1))

Accuracy: 0.9866666666666667


In [80]:
print(classification_report(ytest1,y_pred1))

              precision    recall  f1-score   support

     digit_1       0.98      1.00      0.99       602
     digit_9       0.99      0.98      0.99       598

   micro avg       0.99      0.99      0.99      1200
   macro avg       0.99      0.99      0.99      1200
weighted avg       0.99      0.99      0.99      1200



# digit 3 and digit 6

In [81]:
Data3= Devanagiri[Devanagiri['character']=='digit_3']

In [82]:
Data6= Devanagiri[Devanagiri['character']=='digit_6']

In [84]:
DataNew1=pd.concat([Data3,Data6],axis=0)

In [86]:
DataNew1.shape

(4000, 1025)

In [87]:
DataNew1.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
78000           0           0           0           0           0           0   
78001           0           0           0           0           0           0   
78002           0           0           0           0           0           0   
78003           0           0           0           0           0           0   
78004           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009    ...      pixel_1015  \
78000           0           0           0           0    ...               0   
78001           0           0           0           0    ...               0   
78002           0           0           0           0    ...               0   
78003           0           0           0           0    ...               0   
78004           0           0           0           0    ...               0   

       pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  pixel_1021  \
78000           0           0           0           0           0           0   
78001           0           0           0           0           0           0   
78002           0           0           0           0           0           0   
78003           0           0           0           0           0           0   
78004           0           0           0           0           0           0   

       pixel_1022  pixel_1023  character  
78000           0           0    digit_3  
78001           0           0    digit_3  
78002           0           0    digit_3  
78003           0           0    digit_3  
78004           0           0    digit_3  

[5 rows x 1025 columns]

In [89]:
X3=DataNew1.drop('character',axis=1)
Y3=DataNew1['character']

In [90]:
xtrain2,xtest2,ytrain2,ytest2=train_test_split(X3,Y3,test_size=0.3,random_state=2)

In [92]:
GD=GradientBoostingClassifier(n_estimators=10,learning_rate=0.1)
#n_estimators==number of iterations
#learning_rate=0.1
#base model is DT by default
#here nb i have given as base estimator
model = GD.fit(xtrain2, ytrain2)

y_pred2 = model.predict(xtest2)

In [93]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(ytest2, y_pred2))

Accuracy: 0.9508333333333333


In [95]:
print(confusion_matrix(ytest2,y_pred2))

[[564  38]
 [ 21 577]]


In [96]:
print(classification_report(ytest2,y_pred2))

              precision    recall  f1-score   support

     digit_3       0.96      0.94      0.95       602
     digit_6       0.94      0.96      0.95       598

   micro avg       0.95      0.95      0.95      1200
   macro avg       0.95      0.95      0.95      1200
weighted avg       0.95      0.95      0.95      1200



#  character_19_dha &  character_04_gha

In [97]:
Data_dha= Devanagiri[Devanagiri['character']=='character_19_dha']

In [98]:
Data_gha= Devanagiri[Devanagiri['character']=='character_04_gha']

In [99]:
Data_char=pd.concat([Data_dha,Data_gha],axis=0)

In [100]:
Data_char.shape

(4000, 1025)

In [101]:
Data_char.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
36000           0           0           0           0           0           0   
36001           0           0           0           0           0           0   
36002           0           0           0           0           0           0   
36003           0           0           0           0           0           0   
36004           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009        ...         \
36000           0           0           0           0        ...          
36001           0           0           0           0        ...          
36002           0           0           0           0        ...          
36003           0           0           0           0        ...          
36004           0           0           0           0        ...          

       pixel_1015  pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  \
36000           0           0           0           0           0           0   
36001           0           0           0           0           0           0   
36002           0           0           0           0           0           0   
36003           0           0           0           0           0           0   
36004           0           0           0           0           0           0   

       pixel_1021  pixel_1022  pixel_1023         character  
36000           0           0           0  character_19_dha  
36001           0           0           0  character_19_dha  
36002           0           0           0  character_19_dha  
36003           0           0           0  character_19_dha  
36004           0           0           0  character_19_dha  

[5 rows x 1025 columns]

In [102]:
X4=Data_char.drop('character',axis=1)
Y4=Data_char['character']

In [103]:
xtrain3,xtest3,ytrain3,ytest3=train_test_split(X4,Y4,test_size=0.3,random_state=2)

In [105]:
GD=GradientBoostingClassifier(n_estimators=10,learning_rate=0.1)
#n_estimators==number of iterations
#learning_rate=0.1
#base model is DT by default
#here nb i have given as base estimator
model = GD.fit(xtrain3, ytrain3)

y_pred3 = model.predict(xtest3)

In [106]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(ytest3, y_pred3))

Accuracy: 0.8975


In [107]:
print(confusion_matrix(ytest3,y_pred3))

[[527  71]
 [ 52 550]]


In [108]:
print(classification_report(ytest3,y_pred3))

                  precision    recall  f1-score   support

character_04_gha       0.91      0.88      0.90       598
character_19_dha       0.89      0.91      0.90       602

       micro avg       0.90      0.90      0.90      1200
       macro avg       0.90      0.90      0.90      1200
    weighted avg       0.90      0.90      0.90      1200

