In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn import metrics
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [4]:
admit = pd.read_csv('Admissions.csv')


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76

# QUESTION 1

In [6]:
#This is a Logistic regression plot
#Since it has the probability values and frequency of BMI
#The curve is a sigmoid shape
#Takes values between 0 and 1

# QUESTION 2

In [7]:
#The response variables can take 0 and 1
#It even takes the probability of column that it is being 0 and 1
#when we go with statistical model it shows probability
#when we give model.predict(IV) it gives 0 or 1
#model.predict_proba() it gives probability values

# QUESTION 3

In [295]:
bmi = np.random.normal(25,5,35)
bmi

array([13.47824578, 28.87984803, 21.13712797, 27.69228462, 21.70293487,
       25.34530772, 31.47689677, 21.73016635, 26.13172095, 25.14982117,
       24.97337211, 23.45902334, 21.21452319, 27.42785508, 24.64263787,
       28.80858889, 27.00090796, 26.50707356, 22.05742427, 33.09971511,
       24.22205064, 24.24118746, 25.57725667, 23.94678718, 21.95271121,
       25.44015218, 17.76539797, 21.28897584, 42.36087598, 28.08680356,
       19.58406915, 20.09833118, 20.5919078 , 24.65501594, 24.67282712])

In [296]:
mortality = np.array([0,0,0,0,0,0,1,0,1,0,1,1,0,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,0,1,0,1,1,1,1]) 
mortality

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1])

In [297]:
bmi_da = pd.DataFrame(bmi)
bmi_da['mortality']= mortality
bmi_da.columns = ["bmi", "mortality"]


In [298]:
bmi_da1 = bmi_da.sort_values(by = 'bmi')

In [299]:
bmi_da1

bmi  mortality
0   13.478246          0
26  17.765398          1
30  19.584069          0
31  20.098331          1
32  20.591908          1
2   21.137128          0
12  21.214523          0
27  21.288976          1
4   21.702935          0
7   21.730166          0
24  21.952711          1
18  22.057424          1
11  23.459023          1
23  23.946787          0
20  24.222051          1
21  24.241187          1
14  24.642638          1
33  24.655016          1
34  24.672827          1
10  24.973372          1
9   25.149821          0
5   25.345308          0
25  25.440152          1
22  25.577257          1
8   26.131721          1
17  26.507074          1
16  27.000908          0
13  27.427855          1
3   27.692285          0
29  28.086804          1
15  28.808589          1
1   28.879848          0
6   31.476897          1
19  33.099715          1
28  42.360876          0

In [300]:
#I prefer logistic regression to predict the mortality

In [301]:
#I haven't choose Linear regression because whe have binary variable in the target column
#Linear regression does not classify the variables
#Logistic regression predicts the probability and internally sets the threshold
#If the probability value greater than the threshold value the the mortality goes to 1
#We usually set 0.5 as the threshold limit 

In [302]:
#Assumptions


#The outcome is a binary or dichotomous variable like yes vs no, positive vs negative, 1 vs 0.
#There is a linear relationship between the outcome and each predictor variables. 
#There is no outliers in the predictors (provided the values are continuous)
#There is no high multicollinearity 
#Homoscedacity
#Data is normal
#Data is independent and normal

In [303]:
#Building the model

#Since we have only 35 row dataset we dont need to split into train and test
x = bmi_da1[["bmi"]]
y = bmi_da1[["mortality"]]

log = LogisticRegression()
model = log.fit(x,y)

C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [304]:
#Model performance

y_pred = model.predict(x)

In [305]:
mat = metrics.confusion_matrix(y_pred,y)
accuracy = (mat[0][0]+mat[1][1])/sum(sum(mat))
accuracy

0.6285714285714286

In [306]:
#passing 3 variables
a4 = np.array([31,35,24])
a4 = pd.DataFrame(a4)
a4

0
0  31
1  35
2  24

In [307]:
y_pred = model.predict(a4)
y_pred

array([1, 1, 1])

In [308]:
#For any value it returns 1

In [309]:
x1 = sm.add_constant(x)
model1 = sm.OLS(y,x1).fit()

In [310]:
model1.params

const    0.549905
bmi      0.003178
dtype: float64

In [311]:
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:              mortality   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.029
Method:                 Least Squares   F-statistic:                   0.03318
Date:                Tue, 18 Sep 2018   Prob (F-statistic):              0.857
Time:                        04:13:49   Log-Likelihood:                -24.188
No. Observations:                  35   AIC:                             52.38
Df Residuals:                      33   BIC:                             55.49
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5499      0.440      1.250      0.220      -0.345       1.445
bmi            0.0032      0.017      0.182      0.857      -0.032       0.039
==============================================================================
Omnibus:                       56.907   Durbin-Watson:                   2.209
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                5.929
Skew:                          -0.533   Prob(JB):                       0.0516
Kurtosis:                       1.289   Cond. No.                         132.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [312]:
#P-value is high for bmi and hence bmi is insignificant variable to predict mortality

In [313]:
#Odd's Ratio
#odd's Ration = (p31/(1-p31))/(p32/(1-p32)) where p is the probability of success
#For bmi 31

b31 = model.predict_proba(31)
b32 = model.predict_proba(32)
d = b31/b32
d[:,1]

array([0.99339073])

In [314]:
#odds ratio is 0.99

In [315]:
a5 = np.array([1,1,1])
a5 = pd.DataFrame(a5)
a5['val'] = [31,35,24]
a5.columns = ['Const','val']
a5

Const  val
0      1   31
1      1   35
2      1   24

In [316]:
predictions = model1.predict(a5)
predictions

0    0.648420
1    0.661131
2    0.626174
dtype: float64

In [317]:
#Whatever the method may be we are getting the mortality as 1

# QUESTION 4

In [318]:
admit.head(2)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76

In [319]:
max(admit['Chance of Admit '])

0.97

In [320]:
#i)My Model Preference

#I prefer linear regression to predict the probability


In [321]:
#ii)Why i haven't choose logistic regression

#Even if we use logistic regresstion we could predict the probability but the problem is we are not setting any threshold 
#Threshold is to move it to 0 and 1 
#Building a confusion matrix might be a problem for this dataset
#If we had any emperical data of 0 and 1 we could able to set threshold to 0.6 or 0.5 where i will get more accuracy
#Since we have the probability value which is continuous i will go with Linear regression


In [322]:
#iii)Assumptions

#There should be linear relationship between target and independent variables
#Error variance should be same(Homoskedacity)
#No multicollinearity
#No Autocorrelation
#Data should be normally distributed
#data should be independent and random

In [323]:
#iv)Splitting of data

x = admit.drop(["Chance of Admit ","Serial No."], axis=1)
y = admit[["Chance of Admit "]]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state = 3)

In [324]:
# v) Building Model

x_train1 = sm.add_constant(x_train)
model = sm.OLS(y_train,x_train1).fit()
x_test1 = sm.add_constant(x_test)


In [325]:
y_pred = model.predict(x_test1)

In [281]:
# vi) Model Performance

mse = metrics.mean_squared_error(y_pred,y_test)
rmse = np.sqrt(mse)
rmse

0.06651698559600303

In [282]:
#RMSE value is 0.063
#RSQ value is above 80% 
#We say the model is good predictor
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:       Chance of Admit    R-squared:                       0.807
Model:                            OLS   Adj. R-squared:                  0.802
Method:                 Least Squares   F-statistic:                     162.4
Date:                Tue, 18 Sep 2018   Prob (F-statistic):           2.87e-93
Time:                        04:09:34   Log-Likelihood:                 380.76
No. Observations:                 280   AIC:                            -745.5
Df Residuals:                     272   BIC:                            -716.4
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -1.1327      0.150     -7.558      0.000      -1.428      -0.838
GRE Score             0.0010      0.001      1.321      0.187      -0.000       0.002
TOEFL Score           0.0042      0.001      3.344      0.001       0.002       0.007
University Rating     0.0034      0.005      0.636      0.525      -0.007       0.014
SOP                  -0.0021      0.007     -0.316      0.753      -0.015       0.011
LOR                   0.0257      0.007      3.862      0.000       0.013       0.039
CGPA                  0.1149      0.014      8.023      0.000       0.087       0.143
Research              0.0342      0.010      3.554      0.000       0.015       0.053
==============================================================================
Omnibus:                       59.773   Durbin-Watson:                   1.859
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              119.113
Skew:                          -1.090   Prob(JB):                     1.36e-26
Kurtosis:                       5.336   Cond. No.                     1.33e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.33e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [283]:
# vii) Predicting for given
b = [1,295,98,4,4.5,4.5,7.56,1]
b1 = [1,333,112,4,4.5,4.5,8.87,1]

In [284]:
pr = pd.DataFrame(b).T
pr.columns = ['Const','GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA','Research']
pr.loc[1, :]= b1
pr

Const  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0    1.0      295.0         98.0                4.0  4.5   4.5  7.56       1.0
1    1.0      333.0        112.0                4.0  4.5   4.5  8.87       1.0

In [285]:
predictions = model.predict(pr)
predictions

0    0.586713
1    0.832774
dtype: float64

In [286]:
#First student has probability of 58%
#Second has the probability of 83% to get admit


In [287]:
#P-Values for the model
model.pvalues

const                6.262247e-13
GRE Score            1.874785e-01
TOEFL Score          9.429186e-04
University Rating    5.250633e-01
SOP                  7.525882e-01
LOR                  1.406466e-04
CGPA                 3.092362e-14
Research             4.465463e-04
dtype: float64

In [288]:
#NULL Hypothesis: The variable does not significantly contributes to target variables
#Alternate Hypothesis: The variable significantly contributes to target variables

In [289]:
#From the above p-values we can say that SOP and University Rating does not contribute to the target variables
#Those two are called insignificant variables since p-value>0.05
#P-value is used to predict significant and insignificant variables

In [290]:
#vii) Interpreting coefficients
model.params

const               -1.132745
GRE Score            0.000958
TOEFL Score          0.004224
University Rating    0.003396
SOP                 -0.002075
LOR                  0.025720
CGPA                 0.114896
Research             0.034236
dtype: float64

In [291]:
# 1 mark increase is GRE score will increase the probability of 0.0009 to get admit
# 1 mark increase is TOEFL score will increase the probability of 0.004224 to get admit
# 1 mark increase is UNIVERSITY RANKING will increase the probability of 0.003 to get admit
# 1 mark increase is SOP will decrease the probability of 0.002 to get admit
# 1 mark increase is LOR will increase the probability of 0.025 to get admit
# 1 mark increase is CGPA will increase the probability of 0.11 to get admit
# 1 mark increase is Research will increase the probability of 0.0034 to get admit

In [264]:
x_train = x_train.drop("const", axis=1)

In [265]:
linreg = LinearRegression()
model5 = linreg.fit(x_train,y_train)

In [266]:
y_m = model5.predict(x_test)

In [268]:
mse = metrics.mean_squared_error(y_m,y_test)
rmse = np.sqrt(mse)
rmse

0.06651698559600312

In [269]:
#We are getting the same RMSE by approacing it in statistical as well as in machine learning approach

In [328]:
#Test Accuracy
model5.score(x_test,y_test)

0.7892912397080706